# Generated by Django 3.2.18 on 2023-05-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230513_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fibres',
            new_name='fibers',
        ),
    ]
